# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dcbbea8beb4e90639d6420bf326bc04b"
name = "boa-home-task-AM"
handle = "boa-home-task-am"
application_url = "https://yarn-observation-master-races.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-80.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://yarn-observation-master-races.trycloudflare.com/auth/callback",
  "https://yarn-observation-master-races.trycloudflare.com/auth/shopify/callback",
  "https://yarn-observation-master-races.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
